// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'user_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

UserModel _$UserModelFromJson(Map<String, dynamic> json) => UserModel(
      id: json['id'] as String?,
      planetCode: json['planetCode'] as String?,
      planetPostAuth: (json['planetPostAuth'] as num?)?.toInt(),
      userName: json['userName'] as String?,
      userAvatar: json['userAvatar'],
      userThumbnailAvatar: json['userThumbnailAvatar'],
      gender: json['gender'],
      userProfile: json['userProfile'],
      interests: json['interests'] as List<dynamic>?,
      place: json['place'],
      school: json['school'],
      direction: json['direction'],
      graduationYear: json['graduationYear'],
      company: json['company'],
      job: json['job'],
      github: json['github'],
      blog: json['blog'],
      score: (json['score'] as num?)?.toInt(),
      jobStatus: json['jobStatus'],
      scoreLevel: (json['scoreLevel'] as num?)?.toInt(),
      followeeNum: (json['followeeNum'] as num?)?.toInt(),
      followNum: (json['followNum'] as num?)?.toInt(),
      followStatus: (json['followStatus'] as num?)?.toInt(),
      vipExpireTime: (json['vipExpireTime'] as num?)?.toInt(),
      vipNumber: json['vipNumber'] as String?,
      userRole: json['userRole'] as String?,
      scoreRank: json['scoreRank'],
      postAllThumbNum: json['postAllThumbNum'],
      postAllViewNum: json['postAllViewNum'],
      needGuide: (json['needGuide'] as num?)?.toInt(),
      syncPopupLeftCount: (json['syncPopupLeftCount'] as num?)?.toInt(),
      paymentInfo: json['paymentInfo'],
    );

Map<String, dynamic> _$UserModelToJson(UserModel instance) => <String, dynamic>{
      'id': instance.id,
      'planetCode': instance.planetCode,
      'planetPostAuth': instance.planetPostAuth,
      'userName': instance.userName,
      'userAvatar': instance.userAvatar,
      'userThumbnailAvatar': instance.userThumbnailAvatar,
      'gender': instance.gender,
      'userProfile': instance.userProfile,
      'interests': instance.interests,
      'place': instance.place,
      'school': instance.school,
      'direction': instance.direction,
      'graduationYear': instance.graduationYear,
      'company': instance.company,
      'job': instance.job,
      'github': instance.github,
      'blog': instance.blog,
      'score': instance.score,
      'jobStatus': instance.jobStatus,
      'scoreLevel': instance.scoreLevel,
      'followeeNum': instance.followeeNum,
      'followNum': instance.followNum,
      'followStatus': instance.followStatus,
      'vipExpireTime': instance.vipExpireTime,
      'vipNumber': instance.vipNumber,
      'userRole': instance.userRole,
      'scoreRank': instance.scoreRank,
      'postAllThumbNum': instance.postAllThumbNum,
      'postAllViewNum': instance.postAllViewNum,
      'needGuide': instance.needGuide,
      'syncPopupLeftCount': instance.syncPopupLeftCount,
      'paymentInfo': instance.paymentInfo,
    };
